apiVersion: apps/v1
kind: Deployment
metadata:
  name: adelss04-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adelss04-web-app
  template:
    metadata:
      labels:
        app: adelss04-web-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: adelss04-web-app
        image: kubechallengeacr.azurecr.io/adelss04calicotwebapp:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: AppSettings__cdnBasrUrl
          value: https://calicot-cdn.azureedge.net/
        - name: AppSettings__FullImageContainer
          value: uploads
        - name: AppSettings__ThumbnailContainer
          value: thumbs
        - name: AppSettings__Secret
          value: A wise man once said nothing
        - name: CosmosDb__Account
          value: https://calocotdb-kubechallenge.documents.azure.com:443/
        - name: CosmosDb__DatabaseName
          value: CalicotDB
        - name: CosmosDb__ContainerName
          value: Produits
        - name: CosmosDb__Key
          value: do1mRNihzNHULVc5CaaWr9bJA43qB7yZZ3eVYMgcMtjwxJFWcSVnfAB2c0YPGGUvUEQT1goInxygACDb793tbQ==
        - name: CosmosDb__ConnectionString
          value: DefaultEndpointsProtocol=https;AccountName=stcalicotkubechallenge;AccountKey=PNiBeHqncRaxrmrfGg9WM3Yuqc4McSX/HOjAYVx3Zr/7YFhy/g/nUel0Y63fivxMVkl5P4JhQ1Ay+AStOYEkig==;EndpointSuffix=core.windows.net
        - name: CalicotImages__ConnectionString
          value: DefaultEndpointsProtocol=https;AccountName=stcalicotkubechallenge;AccountKey=PNiBeHqncRaxrmrfGg9WM3Yuqc4McSX/HOjAYVx3Zr/7YFhy/g/nUel0Y63fivxMVkl5P4JhQ1Ay+AStOYEkig==;EndpointSuffix=core.windows.net
        - name: CalicotImages__Key
          value: PNiBeHqncRaxrmrfGg9WM3Yuqc4McSX/HOjAYVx3Zr/7YFhy/g/nUel0Y63fivxMVkl5P4JhQ1Ay+AStOYEkig==
        - name: Authentication__Google__ClientSecret
          value: spzvnEh5lTLv0bo9S-SdwbW
        - name: Authentication__Google__ClientId
          value: 1014581424284-8fnrj0fis18nl0ob7im8lvsj86c9og5f.apps.googleusercontent.com
        - name: JwtPrivateSigningKey
          value: MIIJKgIBAAKCAgEAtCR2Pii+q9C76P2E9ydHYxnBPjJFGT7MvHuQPKpcS9RImfrkobt0LPS/406eWm/tRBvnYD9nDpHJNKN3TjEenFQuDGR4RHcGK/e43SAhTAi7+s0tfAQd6BK4gznIwvs5cWyilh1B7c9sCnxhJ/EYLIe1N2yiD8mhvfojIF4vMYxONIMTGYXy87lnO9zRAdXAZ39YbtmFmQwK8gfXX5d/XVlKy0tc2y5bRY5iXn9kwqwvFlzL6O4vpjhqA5kwsJV7efhL9nU0ACR4dG3zwFR3SAOOSETXjnfmjH2ocga+oa65ToypUz2L1DwnNHt+M5CtDJ9um4dbYaqfBWkjWe3FuGB0GNPS8pbX2nVt76OfHA/QKmxTWvFdPOZnjpg2QhDujyXgoIY731zx5bAklKVoKFma/qfWfCyCSTUzhgu1KQm9swipMsQyNYr9CjbnIlPn4EvrBIbGcIiaRNCLCIlcAuxE/GiH1zBUfeJxfJQmurejp6mBAtASFY08DmUebBz8mlUbB+LXMYKHZ4GK6TecPy0WJU2qRMQ//PKfOa+wkesp4M53SQdpItDp5akTzYUo4rXwk3HPCtemKaSNhyG+EYtZ1CAmPN5sEjU0/x0Dq7SU5o8KhogBm/5HRJ3M9dMRcwD3OcsMl0kW1PPUt04itboS3SlFav90V9uc2YNGpPsCAwEAAQKCAgEAnEZ9ZZNHRhqAybEVZqvmnCw9nk1R8IKwblrrWBWamBYDHcGwEjZipJV22iTb7yzmMo3afX7DUrpaSJX+7BBks827XPjT9OEks4PmFb7H5AQ3v227pbiUkT2cYAsDBVOYE7PgoEWlaj7lRXt9dX8ML6VTKk/Nj9Clxf939Z5/ZoaHWbrUGPJBP/p5ek8n6mWa0q6A8zk1Uv5FiI4Q41a0ITFTV2V7mpFukLriz4PIz7E78DR0mQ/4ukR6g8Cjoq0rPzaN/7LRd8Yr0SWJrjIYgJrFFiDStz+A/CQOu0zql6zSCTixtArSgT3l7PutEeLSnP66n6YfOm0gIzuAdYV2XfYtF+2DT/sGytjqAaLp8GhhT4dXBuqTUfQRFiyBAGvulLj8b/COJ6FWnYPI+h1D93rB0c0EkeqioHRi0lN36UyvhLaFoytKVqqxQYvCG1leYEOcOVK9Xigjj4zGQFMVzjYQIWOM+L64qtWS/tI1effwlBmxn/KeaJDW9OMThe831jwuGUplfNBGAvCWlNmB27RPB0oBn7bU3HA/2aXKYp5AXQinnBj43vdAm4QtwqJoAlIndwvy4v3hcSFLbw1qggvTTgFGutPmyTQkd1NK2u31F3l/VuHo7/NwY2cENmgiFThPe5oKtkFs2jASaSvl7jSS4OuWNQFgEYK4Hm6qGuECggEBAOA8AH0QgxCA8lIFqCqOeR1TuycP5uZ5beWkP7J2LkjPkATd4WsGWiM8P4g5fNCS1au95TxTvsSkfD64N0wnNnd2X88UkUZsEbisohTFgIG3mLA10A7Y+7aaj7qswCbZvvZj91mXTHgRIwt3UVZsiAzXGx0ohLlzLPniroiyEe3pemRnO1wZc0Ra1x8ylw0mwKABJrvMvDvIXkhulzydvTYbev0VzV75muXoJ8NwJ++IKiOEw0Vuz0C01KWL8YakGeeGKKCEqHX7fkrTGUIWKVX/Fk6dhS0Kq/JLxAk7bRvhkywtKe5PrGCPwBKJVt3Z/AErVPpZiFcxbOhouDu5/YMCggEBAM2pcCh035Q2qJi+1nn5+QCnLN6ydEdJ8mW/BT4+Bjuz0/MM4e9n4OLL0Rn5vtsQk3GQ2ySbyf1yGUMV/gV9hJx8uLeMWywIdz560lufy2SVZ4YcQox7628sa9LwrRQbLrLyykWQxE1u6FVciyBi0QgswT0CHPjBvts7vQ8dDdmIQxa2kOYGbiYZPd9zrqlDNgdkR+WoW2LnE07viwlpX0NrjdfFlcV3EZ7ytUZzrgNNnV/iE8oZU/tso9z4xoLTFAq3xYWbhwzIhVA8gmPo85MBmmetXbXZYdbCHYNljb01obyB2yey0jJQXaGq8A6rEwcczUohi++beV5qgliz2SkCggEBANl4V+DzSqmO5XS3F8luM/hFZJUVzxJnYjX9felOxMTIyRxvNFff6TuTCurLFkoSnjfaC6Ded32vKPCLKNYqkaB6paDoiZyK4wUAKJGMmn0z2lnLVuWPe1A1xn99Wz5Sn+nGOfYhzoAD3sEYD0KKL8iENj+pNE/HbC9NsYfRa6IZdiI6HE/OPwRkNY6EOgr/MoH7m903SreQNCB7YSHgucjoDfe2VV9vJNMkvKvG8nRU0slv0RJdzZMrzbBgcPXr4VOxwWUsQ1Vpe6qF4VE+vQgyRSgpjSeJ2gk7gfySLdeEhn+praj6jGt5/wX7PMwcxVM8+0Vx39DwlncwWL1UPJECggEBAL3woexLXH43KOjBP7Yxnr3yp+cZK3j3m45KqF3+zKTxBWvw1u3To4fyszDpTlJl8bauESazVw7jBN/HfO63KPWZ3sNuNnnpa6/hoUwLvb4smgrrKK80d5Ealo6fx0nNfQi6YQN0m0fkiWDk8n07plCFfQaKYBWCYnF5r7c4nyTrywI8JIC9KZe4MkOgRIyAzXJwNFKvdY9XWKbLZz6O+fN7bun7ysIvoK+K+s6RYgIc+Z6nXp2FXOHVSVV40WXb6iOn7B3kMQsmWrFq4QXDDMoVbfQY0nZzyP+eEcHb1dcMpE5EJBJ6/dSIEqGQDNuPNiiYeiTf7Kyji6kedznTCFkCggEAJqiOblMyRP9fgRO8d3NDcNr687Lq0IL/bLTOV5ebrszehkvK9k8vjl6nLMhDTXtb2qzlqjZmr6ktEO5JGJMMmTpoSE/QzJf/YSuUCAULqJ29IoPRQ+xEvuCX/OMLxE1yYrxHUS7D7aJhSLp7zu21RifThEshssFrxLM+xcwuKYe7yOqI+5nUcu8UJTUq97derhbAMXVVBPjfnnlm7h1jtuOODTIAM01p+3jDXhwO24Z63qOMPjRAKiSibQcgt0OmY+V2PQl8d6y6iO2w9zPgUwT5kaaI39/kUris/FKbgcHcWW5/lSNaRIEMVfWZ25ha2p6GprGPp3C7fcdxk6xI6w==
---
apiVersion: v1
kind: Service
metadata:
  name: adelss04-web-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: adelss04-web-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adelss04-web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adelss04-web-api
  template:
    metadata:
      labels:
        app: adelss04-web-api
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: adelss04-web-api
        image: kubechallengeacr.azurecr.io/adelss04calicotapi:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: AppSettings__cdnBasrUrl
          value: https://calicot-cdn.azureedge.net/
        - name: AppSettings__FullImageContainer
          value: uploads
        - name: AppSettings__ThumbnailContainer
          value: thumbs
        - name: AppSettings__Secret
          value: A wise man once said nothing
        - name: CosmosDb__Account
          value: https://calocotdb-kubechallenge.documents.azure.com:443/
        - name: CosmosDb__DatabaseName
          value: CalicotDB
        - name: CosmosDb__ContainerName
          value: Produits
        - name: CosmosDb__Key
          value: do1mRNihzNHULVc5CaaWr9bJA43qB7yZZ3eVYMgcMtjwxJFWcSVnfAB2c0YPGGUvUEQT1goInxygACDb793tbQ==
        - name: CosmosDb__ConnectionString
          value: DefaultEndpointsProtocol=https;AccountName=stcalicotkubechallenge;AccountKey=PNiBeHqncRaxrmrfGg9WM3Yuqc4McSX/HOjAYVx3Zr/7YFhy/g/nUel0Y63fivxMVkl5P4JhQ1Ay+AStOYEkig==;EndpointSuffix=core.windows.net
        - name: CalicotImages__ConnectionString
          value: DefaultEndpointsProtocol=https;AccountName=stcalicotkubechallenge;AccountKey=PNiBeHqncRaxrmrfGg9WM3Yuqc4McSX/HOjAYVx3Zr/7YFhy/g/nUel0Y63fivxMVkl5P4JhQ1Ay+AStOYEkig==;EndpointSuffix=core.windows.net
        - name: CalicotImages__Key
          value: PNiBeHqncRaxrmrfGg9WM3Yuqc4McSX/HOjAYVx3Zr/7YFhy/g/nUel0Y63fivxMVkl5P4JhQ1Ay+AStOYEkig==
        - name: Authentication__Google__ClientSecret
          value: spzvnEh5lTLv0bo9S-SdwbW
        - name: Authentication__Google__ClientId
          value: 1014581424284-8fnrj0fis18nl0ob7im8lvsj86c9og5f.apps.googleusercontent.com
        - name: JwtPrivateSigningKey
          value: MIIJKgIBAAKCAgEAtCR2Pii+q9C76P2E9ydHYxnBPjJFGT7MvHuQPKpcS9RImfrkobt0LPS/406eWm/tRBvnYD9nDpHJNKN3TjEenFQuDGR4RHcGK/e43SAhTAi7+s0tfAQd6BK4gznIwvs5cWyilh1B7c9sCnxhJ/EYLIe1N2yiD8mhvfojIF4vMYxONIMTGYXy87lnO9zRAdXAZ39YbtmFmQwK8gfXX5d/XVlKy0tc2y5bRY5iXn9kwqwvFlzL6O4vpjhqA5kwsJV7efhL9nU0ACR4dG3zwFR3SAOOSETXjnfmjH2ocga+oa65ToypUz2L1DwnNHt+M5CtDJ9um4dbYaqfBWkjWe3FuGB0GNPS8pbX2nVt76OfHA/QKmxTWvFdPOZnjpg2QhDujyXgoIY731zx5bAklKVoKFma/qfWfCyCSTUzhgu1KQm9swipMsQyNYr9CjbnIlPn4EvrBIbGcIiaRNCLCIlcAuxE/GiH1zBUfeJxfJQmurejp6mBAtASFY08DmUebBz8mlUbB+LXMYKHZ4GK6TecPy0WJU2qRMQ//PKfOa+wkesp4M53SQdpItDp5akTzYUo4rXwk3HPCtemKaSNhyG+EYtZ1CAmPN5sEjU0/x0Dq7SU5o8KhogBm/5HRJ3M9dMRcwD3OcsMl0kW1PPUt04itboS3SlFav90V9uc2YNGpPsCAwEAAQKCAgEAnEZ9ZZNHRhqAybEVZqvmnCw9nk1R8IKwblrrWBWamBYDHcGwEjZipJV22iTb7yzmMo3afX7DUrpaSJX+7BBks827XPjT9OEks4PmFb7H5AQ3v227pbiUkT2cYAsDBVOYE7PgoEWlaj7lRXt9dX8ML6VTKk/Nj9Clxf939Z5/ZoaHWbrUGPJBP/p5ek8n6mWa0q6A8zk1Uv5FiI4Q41a0ITFTV2V7mpFukLriz4PIz7E78DR0mQ/4ukR6g8Cjoq0rPzaN/7LRd8Yr0SWJrjIYgJrFFiDStz+A/CQOu0zql6zSCTixtArSgT3l7PutEeLSnP66n6YfOm0gIzuAdYV2XfYtF+2DT/sGytjqAaLp8GhhT4dXBuqTUfQRFiyBAGvulLj8b/COJ6FWnYPI+h1D93rB0c0EkeqioHRi0lN36UyvhLaFoytKVqqxQYvCG1leYEOcOVK9Xigjj4zGQFMVzjYQIWOM+L64qtWS/tI1effwlBmxn/KeaJDW9OMThe831jwuGUplfNBGAvCWlNmB27RPB0oBn7bU3HA/2aXKYp5AXQinnBj43vdAm4QtwqJoAlIndwvy4v3hcSFLbw1qggvTTgFGutPmyTQkd1NK2u31F3l/VuHo7/NwY2cENmgiFThPe5oKtkFs2jASaSvl7jSS4OuWNQFgEYK4Hm6qGuECggEBAOA8AH0QgxCA8lIFqCqOeR1TuycP5uZ5beWkP7J2LkjPkATd4WsGWiM8P4g5fNCS1au95TxTvsSkfD64N0wnNnd2X88UkUZsEbisohTFgIG3mLA10A7Y+7aaj7qswCbZvvZj91mXTHgRIwt3UVZsiAzXGx0ohLlzLPniroiyEe3pemRnO1wZc0Ra1x8ylw0mwKABJrvMvDvIXkhulzydvTYbev0VzV75muXoJ8NwJ++IKiOEw0Vuz0C01KWL8YakGeeGKKCEqHX7fkrTGUIWKVX/Fk6dhS0Kq/JLxAk7bRvhkywtKe5PrGCPwBKJVt3Z/AErVPpZiFcxbOhouDu5/YMCggEBAM2pcCh035Q2qJi+1nn5+QCnLN6ydEdJ8mW/BT4+Bjuz0/MM4e9n4OLL0Rn5vtsQk3GQ2ySbyf1yGUMV/gV9hJx8uLeMWywIdz560lufy2SVZ4YcQox7628sa9LwrRQbLrLyykWQxE1u6FVciyBi0QgswT0CHPjBvts7vQ8dDdmIQxa2kOYGbiYZPd9zrqlDNgdkR+WoW2LnE07viwlpX0NrjdfFlcV3EZ7ytUZzrgNNnV/iE8oZU/tso9z4xoLTFAq3xYWbhwzIhVA8gmPo85MBmmetXbXZYdbCHYNljb01obyB2yey0jJQXaGq8A6rEwcczUohi++beV5qgliz2SkCggEBANl4V+DzSqmO5XS3F8luM/hFZJUVzxJnYjX9felOxMTIyRxvNFff6TuTCurLFkoSnjfaC6Ded32vKPCLKNYqkaB6paDoiZyK4wUAKJGMmn0z2lnLVuWPe1A1xn99Wz5Sn+nGOfYhzoAD3sEYD0KKL8iENj+pNE/HbC9NsYfRa6IZdiI6HE/OPwRkNY6EOgr/MoH7m903SreQNCB7YSHgucjoDfe2VV9vJNMkvKvG8nRU0slv0RJdzZMrzbBgcPXr4VOxwWUsQ1Vpe6qF4VE+vQgyRSgpjSeJ2gk7gfySLdeEhn+praj6jGt5/wX7PMwcxVM8+0Vx39DwlncwWL1UPJECggEBAL3woexLXH43KOjBP7Yxnr3yp+cZK3j3m45KqF3+zKTxBWvw1u3To4fyszDpTlJl8bauESazVw7jBN/HfO63KPWZ3sNuNnnpa6/hoUwLvb4smgrrKK80d5Ealo6fx0nNfQi6YQN0m0fkiWDk8n07plCFfQaKYBWCYnF5r7c4nyTrywI8JIC9KZe4MkOgRIyAzXJwNFKvdY9XWKbLZz6O+fN7bun7ysIvoK+K+s6RYgIc+Z6nXp2FXOHVSVV40WXb6iOn7B3kMQsmWrFq4QXDDMoVbfQY0nZzyP+eEcHb1dcMpE5EJBJ6/dSIEqGQDNuPNiiYeiTf7Kyji6kedznTCFkCggEAJqiOblMyRP9fgRO8d3NDcNr687Lq0IL/bLTOV5ebrszehkvK9k8vjl6nLMhDTXtb2qzlqjZmr6ktEO5JGJMMmTpoSE/QzJf/YSuUCAULqJ29IoPRQ+xEvuCX/OMLxE1yYrxHUS7D7aJhSLp7zu21RifThEshssFrxLM+xcwuKYe7yOqI+5nUcu8UJTUq97derhbAMXVVBPjfnnlm7h1jtuOODTIAM01p+3jDXhwO24Z63qOMPjRAKiSibQcgt0OmY+V2PQl8d6y6iO2w9zPgUwT5kaaI39/kUris/FKbgcHcWW5/lSNaRIEMVfWZ25ha2p6GprGPp3C7fcdxk6xI6w==
---
apiVersion: v1
kind: Service
metadata:
  name: adelss04-web-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: adelss04-web-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adelss04-function
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adelss04-function
  template:
    metadata:
      labels:
        app: adelss04-function
    spec:
      containers:
      - name: adelss04-function
        image: kubechallengeacr.azurecr.io/adelss04calicotfunction:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: AzureWebJobsStorage
          value: DefaultEndpointsProtocol=https;AccountName=stcalicotkubechallenge;AccountKey=PNiBeHqncRaxrmrfGg9WM3Yuqc4McSX/HOjAYVx3Zr/7YFhy/g/nUel0Y63fivxMVkl5P4JhQ1Ay+AStOYEkig==;EndpointSuffix=core.windows.net
        - name: FUNCTIONS_WORKER_RUNTIME
          value: dotnet
---
apiVersion: v1
kind: Service
metadata:
  name: adelss04-function
spec:
  selector:
    app: adelss04-function
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
